# Generated by Django 4.0.5 on 2022-06-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_deadline_todo_deadline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='contents',
            field=models.TextField(blank=True, max_length=300, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline_date',
            field=models.DateField(verbose_name='期日(日付)'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline_time',
            field=models.TimeField(default='00:00:00', verbose_name='期日(時間)'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Todo'),
        ),
    ]
